version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 30
          exit 0
  test:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 30
          exit 0
  test_pass1:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 30
          exit 0
  test_pass2:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 30
          exit 0
  test_fail:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 5
          exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test_pass1:
          requires:
              - test
      - test_pass2:
          requires:
              - test
      - test_fail:
          requires:
              - test
      - build:
          requires:
              - test_pass1
              - test_pass2
