version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 30
          exit 0
  test_pass:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 30
          exit 0
  test_fail:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: |
          sleep 5
          exit 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_pass
      - test_fail
